---
- name: Install Nginx
  package:
    name: nginx
    state: present

- name: Start and enable Nginx
  service:
    name: nginx
    state: started
    enabled: true

- name: Deploy Nginx configuration
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  notify: Reload Nginx
