---
- name: Ensure user exists
  user:
    name: deploy
    state: present
    shell: /bin/bash

- name: Add public key for deploy user
  authorized_key:
    user: deploy
    state: present
    key: "{{ lookup('file', 'files/id_rsa.pub') }}"

