---
- name: Ensure web root exists
  file:
    path: /var/www/html
    state: directory
    mode: '0755'
  become: yes  # Added become for elevated privileges

- name: Upload website tarball
  copy:
    src: webserver.tar
    dest: /tmp/webserver.tar
    mode: '0644'
  become: yes  # Added become for elevated privileges

- name: Debug file existence
  stat:
    path: /tmp/webserver.tar
  register: webserver_tar_stat
  become: yes  # Added become for elevated privileges

- name: Extract website tarball
  unarchive:
    src: /tmp/webserver.tar
    dest: /var/www/html/
    remote_src: yes
    extra_opts: [--strip-components=1]
  become: yes  # Added become for elevated privileges

- name: Set permissions
  file:
    path: /var/www/html
    state: directory
    recurse: yes
    owner: nginx
    group: nginx
    mode: '0755'
  when: ansible_os_family == "RedHat"
  become: yes  # Added become for elevated privileges

- name: Set permissions (Debian)
  file:
    path: /var/www/html
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
    mode: '0755'
  when: ansible_os_family == "Debian"
  become: yes  # Added become for elevated privileges
