---
- name: Ensure web root exists
  file:
    path: /var/www/html
    state: directory
    mode: '0755'

- name: Upload website tarball
  copy:
    src: webserver.tar         # Change if you're using index.tar.xz
    dest: /tmp/webserver.tar   # Or index.tar.xz
    mode: '0644'

- name: Extract website tarball
  unarchive:
    src: /tmp/webserver.tar    # Or index.tar.xz
    dest: /var/www/html/
    remote_src: yes
    extra_opts: [--strip-components=1]  # Optional: avoids nested folders

- name: Set permissions
  file:
    path: /var/www/html
    state: directory
    recurse: yes
    owner: nginx
    group: nginx
    mode: '0755'
  when: ansible_os_family == "RedHat"

- name: Set permissions (Debian)
  file:
    path: /var/www/html
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
    mode: '0755'
  when: ansible_os_family == "Debian"
